# Generated by Django 4.0.3 on 2022-03-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locacion',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
