# Generated by Django 4.0.3 on 2022-03-16 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locacion', '0002_alter_locacion_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locacion',
            name='activo',
        ),
    ]
