# Generated by Django 4.0.3 on 2022-03-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locacion', '0003_remove_locacion_activo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locacion',
            old_name='nombre',
            new_name='area',
        ),
        migrations.AddField(
            model_name='locacion',
            name='localizacion',
            field=models.CharField(default=11, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locacion',
            name='puesto',
            field=models.CharField(default=11, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locacion',
            name='sitio',
            field=models.CharField(default=11, max_length=50),
            preserve_default=False,
        ),
    ]
