# Generated by Django 4.0.3 on 2022-03-29 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activo', '0016_remove_activocelular_locacion_and_more'),
        ('locacion', '0004_rename_nombre_locacion_area_locacion_localizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locacion',
            name='activo_industrial',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='activo.activoindustrial'),
            preserve_default=False,
        ),
    ]
