# Generated by Django 4.0.3 on 2022-03-29 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activo', '0017_remove_activocelular_fecha_entrega_and_more'),
        ('locacion', '0005_locacion_activo_industrial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locacion',
            name='puesto',
        ),
        migrations.AddField(
            model_name='locacion',
            name='activo_celular',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activo.activocelular'),
        ),
        migrations.AddField(
            model_name='locacion',
            name='activo_general',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activo.activogeneral'),
        ),
        migrations.AddField(
            model_name='locacion',
            name='activo_notebook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activo.activonotebook'),
        ),
        migrations.AddField(
            model_name='locacion',
            name='activo_standar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activo.activostandar'),
        ),
        migrations.AlterField(
            model_name='locacion',
            name='activo_industrial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activo.activoindustrial'),
        ),
    ]
