# Generated by Django 4.0.3 on 2022-06-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locacion', '0008_alter_locacion_activo_celular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locacion',
            name='nave',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='locacion',
            name='unidad_negocio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
