# Generated by Django 4.0.3 on 2022-03-29 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activo', '0017_remove_activocelular_fecha_entrega_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocacionProductiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitio', models.CharField(max_length=50)),
                ('linea', models.CharField(max_length=10)),
                ('puesto', models.CharField(max_length=20)),
                ('activo_industrial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activo.activoindustrial')),
            ],
        ),
    ]
