# Generated by Django 4.0.3 on 2022-04-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locacion_productiva', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locacionproductiva',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
