# Generated by Django 4.0.3 on 2022-06-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locacion_productiva', '0002_locacionproductiva_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='locacionproductiva',
            name='nave',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='locacionproductiva',
            name='unidad_negocio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
