# Generated by Django 4.0.3 on 2022-03-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_inventario', models.IntegerField()),
                ('numero_serie', models.IntegerField()),
                ('descripcion', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('hostname', models.CharField(max_length=10)),
                ('tipo', models.CharField(max_length=10)),
                ('fabricante', models.CharField(max_length=10)),
                ('modelo', models.CharField(max_length=10)),
            ],
        ),
    ]
