# Generated by Django 4.0.3 on 2022-03-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='numero_inventario',
            field=models.CharField(max_length=10),
        ),
    ]
