# Generated by Django 4.0.3 on 2022-03-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activo', '0003_alter_activo_numero_serie'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='planta',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activo',
            name='unidad_negocio',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
