# Generated by Django 4.0.3 on 2022-03-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activo', '0004_activo_planta_activo_unidad_negocio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='activo',
            name='fabricante',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='activo',
            name='hostname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='activo',
            name='modelo',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='activo',
            name='numero_inventario',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='activo',
            name='numero_serie',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='activo',
            name='planta',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='activo',
            name='tipo',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='activo',
            name='unidad_negocio',
            field=models.CharField(max_length=30),
        ),
    ]
