# Generated by Django 4.0.3 on 2022-03-18 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_usuario_correo'),
        ('activo', '0006_activogeneral_activoindustrial_activostandar_celular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activostandar',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='celular',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notebook',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario'),
            preserve_default=False,
        ),
    ]
