# Generated by Django 4.0.3 on 2022-03-18 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activo', '0007_activostandar_usuario_celular_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activoindustrial',
            name='username',
        ),
    ]
