# Generated by Django 4.0.3 on 2022-03-18 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linea_telefonica', '0001_initial'),
        ('usuario', '0002_alter_usuario_correo'),
        ('activo', '0011_alter_activoindustrial_dpi_alter_activoindustrial_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='celular',
            name='linea_telefonica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='linea_telefonica.lineatelefonica'),
        ),
        migrations.AlterField(
            model_name='activostandar',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario'),
        ),
        migrations.AlterField(
            model_name='celular',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario'),
        ),
    ]
