# Generated by Django 4.0.3 on 2022-03-19 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locacion', '0004_rename_nombre_locacion_area_locacion_localizacion_and_more'),
        ('linea_telefonica', '0002_alter_lineatelefonica_numero'),
        ('usuario', '0002_alter_usuario_correo'),
        ('activo', '0012_celular_linea_telefonica_alter_activostandar_usuario_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Celular',
            new_name='ActivoCelular',
        ),
        migrations.RenameModel(
            old_name='Notebook',
            new_name='ActivoNotebook',
        ),
    ]
