# Generated by Django 4.0.3 on 2022-03-21 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activo', '0013_rename_celular_activocelular_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activogeneral',
            old_name='descipcion',
            new_name='descripcion',
        ),
    ]
