# Generated by Django 4.0.3 on 2022-03-29 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activo', '0015_alter_activonotebook_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activocelular',
            name='locacion',
        ),
        migrations.RemoveField(
            model_name='activogeneral',
            name='locacion',
        ),
        migrations.RemoveField(
            model_name='activoindustrial',
            name='locacion',
        ),
        migrations.RemoveField(
            model_name='activonotebook',
            name='locacion',
        ),
        migrations.RemoveField(
            model_name='activostandar',
            name='locacion',
        ),
    ]
