# Generated by Django 4.0.3 on 2022-03-29 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activo', '0016_remove_activocelular_locacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activocelular',
            name='fecha_entrega',
        ),
        migrations.RemoveField(
            model_name='activocelular',
            name='linea_telefonica',
        ),
        migrations.RemoveField(
            model_name='activocelular',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='activogeneral',
            name='fecha_mantenimiento',
        ),
        migrations.RemoveField(
            model_name='activoindustrial',
            name='fecha_mantenimiento',
        ),
        migrations.RemoveField(
            model_name='activonotebook',
            name='fecha_entrega',
        ),
        migrations.RemoveField(
            model_name='activonotebook',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='activostandar',
            name='fecha_mantenimiento',
        ),
        migrations.RemoveField(
            model_name='activostandar',
            name='usuario',
        ),
    ]
