# Generated by Django 4.0.3 on 2022-04-27 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activo', '0017_remove_activocelular_fecha_entrega_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activocelular',
            name='imei',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='activostandar',
            name='ip',
            field=models.CharField(max_length=50),
        ),
    ]
