# Generated by Django 4.0.3 on 2022-04-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activo', '0019_remove_activocelular_costo_remove_activocelular_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activocelular',
            name='inventario',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='activogeneral',
            name='inventario',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='activoindustrial',
            name='inventario',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='activonotebook',
            name='inventario',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='activostandar',
            name='inventario',
            field=models.CharField(max_length=50),
        ),
    ]
