# Generated by Django 4.0.3 on 2022-05-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activo', '0020_alter_activocelular_inventario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activocelular',
            name='inventario',
        ),
        migrations.AlterField(
            model_name='activoindustrial',
            name='dpi',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='activoindustrial',
            name='ip',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
