# Generated by Django 4.0.3 on 2022-04-12 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locacion', '0007_locacion_fecha'),
        ('locacion_productiva', '0002_locacionproductiva_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trazabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locacion.locacion')),
                ('locacion_productiva', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locacion_productiva.locacionproductiva')),
            ],
        ),
    ]
