# Generated by Django 4.0.3 on 2022-04-12 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locacion', '0007_locacion_fecha'),
        ('locacion_productiva', '0002_locacionproductiva_fecha'),
        ('trazabilidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trazabilidad',
            name='locacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locacion.locacion'),
        ),
        migrations.AlterField(
            model_name='trazabilidad',
            name='locacion_productiva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locacion_productiva.locacionproductiva'),
        ),
    ]
