# Generated by Django 4.0.3 on 2022-06-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trazabilidad', '0002_alter_trazabilidad_locacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trazabilidad',
            name='area',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trazabilidad',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trazabilidad',
            name='localizacion',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trazabilidad',
            name='nave',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trazabilidad',
            name='sitio',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trazabilidad',
            name='unidad_negocio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
