# Generated by Django 4.0.3 on 2022-04-27 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linea_telefonica', '0002_alter_lineatelefonica_numero'),
        ('usuario', '0003_usuario_activo_celular_usuario_activo_notebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='linea_telefonica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='linea_telefonica.lineatelefonica'),
        ),
    ]
