# Generated by Django 4.0.3 on 2022-05-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_alter_usuario_activo_celular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='legajo',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
