# Generated by Django 4.0.3 on 2022-03-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linea_telefonica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineatelefonica',
            name='numero',
            field=models.CharField(max_length=50),
        ),
    ]
